name: 酒店源采集

on:
  schedule:
    - cron: '25 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install selenium requests futures eventlet replace input

      - name: Run iptv
        run: python ${{ github.workspace }}/酒店源采集/iptv.py

      - name: 提交更改
        run: |
          git config --local user.email "actions@126.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Add generated file"
            git push -f
          else
            echo "No changes to commit."
          fi
